name: panvimdoc

on:
  push:
    paths: ["**.md"]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    name: README to vimdoc
    steps:
      - uses: actions/checkout@v4

      - uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: "auto-dark-mode"
          description: "sync nvim with your desktop environment's appearance"
          demojify: true

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: auto-generate vimdoc"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          branch: ${{ github.head_ref }}
